title: Hello World
description: >-
  Hie I am Rutvi. This is my first repository and I am still learning that how
  things work here.
template:
  repo: hello-world-template
  name: hello-world
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
